[profile.default]
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    "solady/src=lib/solady/src"
]
[profile.ci.fuzz]
runs = 1
depth = 1
fail_on_revert = true